# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'UniAlarmee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.7.3'
  # Pods for UniAlarmee

  target 'UniAlarmeeTests' do
    pod 'Alamofire', '4.7.3'
  end

  target 'UniAlarmeeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
