# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'how_to_use_webview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
     pod 'Alamofire', '~> 4.7.3'

  # Pods for how_to_use_webview

end
