# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'trylog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.7.3'
  # Pods for trylog

  target 'trylogTests' do
	pod 'Alamofire', '~> 4.7.3'
    inherit! :search_paths
    # Pods for testing
  end

  target 'trylogUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
